---
development:
  cloud_name: toshiloco
  api_key: '892699781155175'
  api_secret: 8wGYFQmCTkYWmYdheDulpXilKdA
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: toshiloco
  api_key: '892699781155175'
  api_secret: 8wGYFQmCTkYWmYdheDulpXilKdA
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: toshiloco
  api_key: '892699781155175'
  api_secret: 8wGYFQmCTkYWmYdheDulpXilKdA
  enhance_image_tag: true
  static_image_support: false
